<a href="https://colab.research.google.com/github/Charan-077/21083133_project_football/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as foot_ba_pd
import numpy as foot_ba_np
import matplotlib.pyplot as foot_ba_plt
import seaborn as foot_ba_sns
import sqlite3 as foot_ba_sqlite
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
def tables_in_sqlite_db(conn):
    cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [
        v[0] for v in cursor.fetchall()
        if v[0] != "sqlite_sequence"
    ]
    cursor.close()
    return tables

In [6]:
sqlite3_conn = foot_ba_sqlite.connect('/content/drive/MyDrive/Database/database.sqlite')

In [7]:
tables = tables_in_sqlite_db(sqlite3_conn)

In [8]:
tables

['betfront', 'football_data']

In [9]:
# Saving the raw data in a dictionary as pandas dataframes

foot_ba_dict = {}

for table in tables:
    foot_ba_dict[table] = foot_ba_pd.read_sql_query("SELECT * FROM '{}'".format(table), sqlite3_conn)

In [10]:
foot_ba = foot_ba_dict["football_data"]

In [11]:
foot_ba

,Season,Datetime,Div,Country,League,Referee,HomeTeam,AwayTeam,FTHG,FTAG,...,VCCD,VCCH,VCD,VCH,WHA,WHCA,WHCD,WHCH,WHD,WHH
0,2021,2021-05-31 23:00:00,ARG,Argentina,Primera Division,None,Independiente,Colon Santa FE,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021-05-31 19:00:00,ARG,Argentina,Primera Division,None,Racing Club,Boca Juniors,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021-05-31 02:30:00,USA,USA,MLS,None,Seattle Sounders,Austin FC,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020/2021,2021-05-31 02:15:00,MEX,Mexico,Liga MX,None,Cruz Azul,Santos Laguna,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021-05-31 00:30:00,BRA,Brazil,Serie A,None,Internacional,Sport Recife,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190668,2000/2001,2000-07-29 00:00:00,F2,France,Division 2,None,Ajaccio,Le Mans,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190669,2000/2001,2000-07-29 00:00:00,SC0,Scotland,Premier League,Willie Young,St Mirren,Kilmarnock,0,1,...,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,3.25,2.40
190670,2000/2001,2000-07-28 00:00:00,F1,France,Le Championnat,None,Paris SG,Strasbourg,3,1,...,NaN,NaN,NaN,NaN,6.5,NaN,NaN,NaN,3.70,1.40
190671,2000/2001,2000-07-28 00:00:00,F1,France,Le Championnat,None,Marseille,Troyes,3,1,...,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,3.50,1.45
190672,2000/2001,2000-07-28 00:00:00,F2,France,Division 2,None,Wasquehal,Nancy,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
foot_ba["Country_League"] = foot_ba["Country"] + "_" + foot_ba["League"]

In [13]:
foot_ba["Country_League"]

0         Argentina_Primera Division
1         Argentina_Primera Division
2                            USA_MLS
3                     Mexico_Liga MX
4                     Brazil_Serie A
                     ...
190668             France_Division 2
190669       Scotland_Premier League
190670         France_Le Championnat
190671         France_Le Championnat
190672             France_Division 2
Name: Country_League, Length: 190673, dtype: object

In [14]:
foot_ba.shape

(190673, 173)

In [15]:
foot_ba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190673 entries, 0 to 190672
Columns: 173 entries, Season to Country_League
dtypes: float64(151), int64(4), object(18)
memory usage: 251.7+ MB

In [16]:
foot_ba.isnull().sum()

Season                 0
Datetime               0
Div                    0
Country                0
League                 0
                   ...
WHCD              176267
WHCH              176267
WHD                43664
WHH                43664
Country_League         0
Length: 173, dtype: int64

In [17]:
def display_na_cols(df):
    with foot_ba_pd.option_context("display.min_rows", 50, "display.max_rows", 200, "display.max_columns", 5):
        display(df[df.columns[df.isna().any()]].isnull().sum())

In [18]:
# Create an id column tha represents the index from the very first dataset "foot_ba" (in case we need to relate somehow and also just to have an unique key-column per observation.)
foot_ba = foot_ba.reset_index().rename({"index":"index_id"},axis=1)

In [19]:
foot_ba_columns_1 = ["index_id", "Div", "Date", "Time", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "Attendance", "Referee", "HS", "AS", "HST", "AST", "HHW", "AHW", "HC", "HF", "AF", "HFKC", "AFKC", "AO", "HY", "AY", "HR", "AR", "HBP", "ABP", "HTHG", "HTAG", "HTR", "FTR"]

In [20]:
foot_ba_1 = foot_ba[foot_ba_columns_1]

In [21]:
foot_ba_1.dtypes

index_id        int64
Div            object
Date           object
Time           object
HomeTeam       object
AwayTeam       object
FTHG            int64
FTAG            int64
Attendance    float64
Referee        object
HS            float64
AS            float64
HST           float64
AST           float64
HHW           float64
AHW           float64
HC            float64
HF            float64
AF            float64
HFKC          float64
AFKC          float64
AO            float64
HY            float64
AY            float64
HR            float64
AR            float64
HBP           float64
ABP           float64
HTHG            int64
HTAG            int64
HTR            object
FTR            object
dtype: object